### ISSUE TITLE
GrassBendingManager.AddBender() has useless code which impacts performance

### ISSUE THREAD

**Issue by JeReT** [Elringus/GrassBending#4]
The method I think has a performance issue is the following.
```
        public static void AddBender (IGrassBender bender)
        {
            if (!benders.Add(bender)) return;

            // SortedSet generates garbage on enumeration, so hacking with linq here.
            var sortedBenders = benders.OrderBy(b => b.Priority).ToList();
            benders.Clear();
            benders.UnionWith(sortedBenders);
        }
```
From my understanding it is like this:
A Hashset (benders) will always be sorted by Hash, it doesn't change the order if it is ordered by prio, converted to list, cleared and united with the list again...
This is just a big performance issue which does nothing in the end.

The Hashset will be in the excact same order after these lines.

Therefore, I think the method can simply be like this:
```
        public static void AddBender (IGrassBender bender)
        {
            benders.Add(bender);
        }
```
And you should make sure that all implementations of `IGrassBender `override `GetHashCode()` and return their priority there (if you really require order by priority).

**Comment by elringus** [comment]
Iirc, the order was actually preserved the last time I've used this package; though, it may have been the case for the specific platform or scripting backend I've been targeting. Anyway, that's definitely not the best solution. I've made some changes in the last update (https://github.com/Elringus/GrassBending/commit/ca18da0a0b2af831b085a7a4989e67228efde540#diff-7769b297af2523df2130328c9c94b48621af738d10523c1a5116f5a267f926a6R25), so it should hopefully be both faster and stable across the platforms. Thanks for noticing!
